local addonName, addon = ...

local LSM = LibStub("LibSharedMedia-3.0")
local effectPath = "Interface\\AddOns\\" .. addonName .. "\\Sounds\\Effects\\"
local voiceoverPath = "Interface\\AddOns\\" .. addonName .. "\\Sounds\\Voiceovers\\"

-- Soundeffects
LSM:Register("sound", "For the Horde", effectPath .. "bloodlust.ogg")
LSM:Register("sound", "EQOL: Bite", effectPath .. "cartoonbite.ogg")
LSM:Register("sound", "EQOL: Punch", effectPath .. "gamingpunch.ogg")

-- Voiceovers
LSM:Register("sound", "EQOL: 1", voiceoverPath .. "1.ogg")
LSM:Register("sound", "EQOL: 2", voiceoverPath .. "2.ogg")
LSM:Register("sound", "EQOL: 3", voiceoverPath .. "3.ogg")
LSM:Register("sound", "EQOL: 4", voiceoverPath .. "4.ogg")
LSM:Register("sound", "EQOL: 5", voiceoverPath .. "5.ogg")
LSM:Register("sound", "EQOL: 6", voiceoverPath .. "6.ogg")
LSM:Register("sound", "EQOL: 7", voiceoverPath .. "7.ogg")
LSM:Register("sound", "EQOL: 8", voiceoverPath .. "8.ogg")
LSM:Register("sound", "EQOL: 9", voiceoverPath .. "9.ogg")
LSM:Register("sound", "EQOL: 10", voiceoverPath .. "10.ogg")
LSM:Register("sound", "EQOL: First", voiceoverPath .. "First.ogg")
LSM:Register("sound", "EQOL: Second", voiceoverPath .. "Second.ogg")
LSM:Register("sound", "EQOL: Third", voiceoverPath .. "Third.ogg")
LSM:Register("sound", "EQOL: Fourth", voiceoverPath .. "Fourth.ogg")
LSM:Register("sound", "EQOL: Fifth", voiceoverPath .. "Fifth.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|tStar", voiceoverPath .. "Star.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|tCircle", voiceoverPath .. "Circle.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|tDiamond", voiceoverPath .. "Diamond.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|tTriangle", voiceoverPath .. "Triangle.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|tMoon", voiceoverPath .. "Moon.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|tSquare", voiceoverPath .. "Square.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|tCross", voiceoverPath .. "Cross.ogg")
LSM:Register("sound", "EQOL: |TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|tSkull", voiceoverPath .. "Skull.ogg")
LSM:Register("sound", "EQOL: Adds", voiceoverPath .. "Adds.ogg")
LSM:Register("sound", "EQOL: Add", voiceoverPath .. "Add.ogg")
LSM:Register("sound", "EQOL: Affix", voiceoverPath .. "Affix.ogg")
LSM:Register("sound", "EQOL: AoE", voiceoverPath .. "AoE.ogg")
LSM:Register("sound", "EQOL: Assist", voiceoverPath .. "Assist.ogg")
LSM:Register("sound", "EQOL: Avoid", voiceoverPath .. "Avoid.ogg")
LSM:Register("sound", "EQOL: Back", voiceoverPath .. "Back.ogg")
LSM:Register("sound", "EQOL: Backup", voiceoverPath .. "Backup.ogg")
LSM:Register("sound", "EQOL: Bait", voiceoverPath .. "Bait.ogg")
LSM:Register("sound", "EQOL: Beam", voiceoverPath .. "Beam.ogg")
LSM:Register("sound", "EQOL: Bleed", voiceoverPath .. "Bleed.ogg")
LSM:Register("sound", "EQOL: Blue", voiceoverPath .. "Blue.ogg")
LSM:Register("sound", "EQOL: Bombs", voiceoverPath .. "Bombs.ogg")
LSM:Register("sound", "EQOL: Boss", voiceoverPath .. "Boss.ogg")
LSM:Register("sound", "EQOL: Break", voiceoverPath .. "Break.ogg")
LSM:Register("sound", "EQOL: Buff", voiceoverPath .. "Buff.ogg")
LSM:Register("sound", "EQOL: CC", voiceoverPath .. "CC.ogg")
LSM:Register("sound", "EQOL: Chain", voiceoverPath .. "Chain.ogg")
LSM:Register("sound", "EQOL: Charge", voiceoverPath .. "Charge.ogg")
LSM:Register("sound", "EQOL: Check", voiceoverPath .. "Check.ogg")
LSM:Register("sound", "EQOL: Clear", voiceoverPath .. "Clear.ogg")
LSM:Register("sound", "EQOL: Collect", voiceoverPath .. "Collect.ogg")
LSM:Register("sound", "EQOL: Dance", voiceoverPath .. "Dance.ogg")
LSM:Register("sound", "EQOL: Debuff", voiceoverPath .. "Debuff.ogg")
LSM:Register("sound", "EQOL: Decurse", voiceoverPath .. "Decurse.ogg")
LSM:Register("sound", "EQOL: Defensive", voiceoverPath .. "Defensive.ogg")
LSM:Register("sound", "EQOL: Dispell", voiceoverPath .. "Dispell.ogg")
LSM:Register("sound", "EQOL: Dodge", voiceoverPath .. "Dodge.ogg")
LSM:Register("sound", "EQOL: Dot", voiceoverPath .. "Dot.ogg")
LSM:Register("sound", "EQOL: Don't", voiceoverPath .. "Don't.ogg")
LSM:Register("sound", "EQOL: Don't move", voiceoverPath .. "Don't move.ogg")
LSM:Register("sound", "EQOL: Drop", voiceoverPath .. "Drop.ogg")
LSM:Register("sound", "EQOL: Enrage", voiceoverPath .. "Enrage.ogg")
LSM:Register("sound", "EQOL: Enter", voiceoverPath .. "Enter.ogg")
LSM:Register("sound", "EQOL: Exit", voiceoverPath .. "Exit.ogg")
LSM:Register("sound", "EQOL: External", voiceoverPath .. "External.ogg")
LSM:Register("sound", "EQOL: Fear", voiceoverPath .. "Fear.ogg")
LSM:Register("sound", "EQOL: Feet", voiceoverPath .. "Feet.ogg")
LSM:Register("sound", "EQOL: Fixate", voiceoverPath .. "Fixate.ogg")
LSM:Register("sound", "EQOL: Focus", voiceoverPath .. "Focus.ogg")
LSM:Register("sound", "EQOL: Frontal", voiceoverPath .. "Frontal.ogg")
LSM:Register("sound", "EQOL: Gate", voiceoverPath .. "Gate.ogg")
LSM:Register("sound", "EQOL: Gather", voiceoverPath .. "Gather.ogg")
LSM:Register("sound", "EQOL: Green", voiceoverPath .. "Green.ogg")
LSM:Register("sound", "EQOL: Go", voiceoverPath .. "Go.ogg")
LSM:Register("sound", "EQOL: Grip", voiceoverPath .. "Grip.ogg")
LSM:Register("sound", "EQOL: Hide", voiceoverPath .. "Hide.ogg")
LSM:Register("sound", "EQOL: Immunity", voiceoverPath .. "Immunity.ogg")
LSM:Register("sound", "EQOL: In", voiceoverPath .. "In.ogg")
LSM:Register("sound", "EQOL: Intermission", voiceoverPath .. "Intermission.ogg")
LSM:Register("sound", "EQOL: Interrupt", voiceoverPath .. "Interrupt.ogg")
LSM:Register("sound", "EQOL: Invis", voiceoverPath .. "Invis.ogg")
LSM:Register("sound", "EQOL: Invisibility", voiceoverPath .. "Invisibility.ogg")
LSM:Register("sound", "EQOL: Jump", voiceoverPath .. "Jump.ogg")
LSM:Register("sound", "EQOL: Kick", voiceoverPath .. "Kick.ogg")
LSM:Register("sound", "EQOL: Kite", voiceoverPath .. "Kite.ogg")
LSM:Register("sound", "EQOL: Knock", voiceoverPath .. "Knock.ogg")
LSM:Register("sound", "EQOL: Last", voiceoverPath .. "Last.ogg")
LSM:Register("sound", "EQOL: Leap", voiceoverPath .. "Leap.ogg")
LSM:Register("sound", "EQOL: Left", voiceoverPath .. "Left.ogg")
LSM:Register("sound", "EQOL: Line", voiceoverPath .. "Line.ogg")
LSM:Register("sound", "EQOL: Line of Sight", voiceoverPath .. "Line of Sight.ogg")
LSM:Register("sound", "EQOL: Link", voiceoverPath .. "Link.ogg")
LSM:Register("sound", "EQOL: Linked", voiceoverPath .. "Linked.ogg")
LSM:Register("sound", "EQOL: LoS", voiceoverPath .. "LoS.ogg")
LSM:Register("sound", "EQOL: Move", voiceoverPath .. "Move.ogg")
LSM:Register("sound", "EQOL: Next", voiceoverPath .. "Next.ogg")
LSM:Register("sound", "EQOL: Nuke", voiceoverPath .. "Nuke.ogg")
LSM:Register("sound", "EQOL: Orange", voiceoverPath .. "Orange.ogg")
LSM:Register("sound", "EQOL: Out", voiceoverPath .. "Out.ogg")
LSM:Register("sound", "EQOL: Overlap", voiceoverPath .. "Overlap.ogg")
LSM:Register("sound", "EQOL: Poison", voiceoverPath .. "Poison.ogg")
LSM:Register("sound", "EQOL: Pot", voiceoverPath .. "Pot.ogg")
LSM:Register("sound", "EQOL: Pull", voiceoverPath .. "Pull.ogg")
LSM:Register("sound", "EQOL: Purple", voiceoverPath .. "Purple.ogg")
LSM:Register("sound", "EQOL: Push", voiceoverPath .. "Push.ogg")
LSM:Register("sound", "EQOL: Ready Check", voiceoverPath .. "Ready Check.ogg")
LSM:Register("sound", "EQOL: Red", voiceoverPath .. "Red.ogg")
LSM:Register("sound", "EQOL: Reflect", voiceoverPath .. "Reflect.ogg")
LSM:Register("sound", "EQOL: Refresh", voiceoverPath .. "Refresh.ogg")
LSM:Register("sound", "EQOL: Right", voiceoverPath .. "Right.ogg")
LSM:Register("sound", "EQOL: Root", voiceoverPath .. "Root.ogg")
LSM:Register("sound", "EQOL: Shield", voiceoverPath .. "Shield.ogg")
LSM:Register("sound", "EQOL: Soak", voiceoverPath .. "Soak.ogg")
LSM:Register("sound", "EQOL: Soon", voiceoverPath .. "Soon.ogg")
LSM:Register("sound", "EQOL: Spawn", voiceoverPath .. "Spawn.ogg")
LSM:Register("sound", "EQOL: Split", voiceoverPath .. "Split.ogg")
LSM:Register("sound", "EQOL: Spread", voiceoverPath .. "Spread.ogg")
LSM:Register("sound", "EQOL: Stack", voiceoverPath .. "Stack.ogg")
LSM:Register("sound", "EQOL: Stay", voiceoverPath .. "Stay.ogg")
LSM:Register("sound", "EQOL: Stop", voiceoverPath .. "Stop.ogg")
LSM:Register("sound", "EQOL: Stopcast", voiceoverPath .. "Stopcast.ogg")
LSM:Register("sound", "EQOL: Swap", voiceoverPath .. "Swap.ogg")
LSM:Register("sound", "EQOL: Switch", voiceoverPath .. "Switch.ogg")
LSM:Register("sound", "EQOL: Stun", voiceoverPath .. "Stun.ogg")
LSM:Register("sound", "EQOL: Targeted", voiceoverPath .. "Targeted.ogg")
LSM:Register("sound", "EQOL: Taunt", voiceoverPath .. "Taunt.ogg")
LSM:Register("sound", "EQOL: Transission", voiceoverPath .. "Transission.ogg")
LSM:Register("sound", "EQOL: Turn", voiceoverPath .. "Turn.ogg")
LSM:Register("sound", "EQOL: Use", voiceoverPath .. "Use.ogg")
LSM:Register("sound", "EQOL: Volley", voiceoverPath .. "Volley.ogg")
LSM:Register("sound", "EQOL: Wave", voiceoverPath .. "Wave.ogg")
LSM:Register("sound", "EQOL: Winds", voiceoverPath .. "Winds.ogg")
LSM:Register("sound", "EQOL: Yellow", voiceoverPath .. "Yellow.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rAMZ |T237510:16|t", voiceoverPath .. "AMZ.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rDarkness |T1305154:16|t", voiceoverPath .. "Darkness.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rBarkskin |T572025:16|t", voiceoverPath .. "Barkskin.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rIronbark |T572025:16|t", voiceoverPath .. "Ironbark.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rIncarnation |T571586:16|t", voiceoverPath .. "Incarnation.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rInnervate |T136048:16|t", voiceoverPath .. "Innervate.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRage of the Sleeper |T1129695:16|t", voiceoverPath .. "Rage of the Sleeper.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRoar |T463283:16|t", voiceoverPath .. "Roar.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rTranquility |T136107:16|t", voiceoverPath .. "Tranquility.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRescue |T4622460:16|t", voiceoverPath .. "Rescue.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRewind |T4622474:16|t", voiceoverPath .. "Rewind.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSpatial Paradox |T5199645:16|t", voiceoverPath .. "Spatial Paradox.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rTime Dilation |T4622478:16|t", voiceoverPath .. "Time Dilation.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rTime Spiral |T4622479:16|t", voiceoverPath .. "Time Spiral.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rMisdirection |T132180:16|t", voiceoverPath .. "Misdirection.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSpellsteal |T135729:16|t", voiceoverPath .. "Spellsteal.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rChi-Ji |T877514:16|t", voiceoverPath .. "Chi-Ji.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rCocoon |T627485:16|t", voiceoverPath .. "Cocoon.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRevival |T1020466:16|t", voiceoverPath .. "Revival.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rTiger's Lust |T651727:16|t", voiceoverPath .. "Tiger's Lust.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rAutumn |T3636843:16|t", voiceoverPath .. "Autumn.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rFreedom |T135968:16|t", voiceoverPath .. "Freedom.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rDevotion Aura |T135893:16|t", voiceoverPath .. "Devotion Aura.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rLay on Hands |T135928:16|t", voiceoverPath .. "Lay on Hands.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rProtection |T135964:16|t", voiceoverPath .. "Protection.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSpellwarding |T135880:16|t", voiceoverPath .. "Spellwarding.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSac |T135966:16|t", voiceoverPath .. "Sac.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSpring |T3636844:16|t", voiceoverPath .. "Spring.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSummer |T3636845:16|t", voiceoverPath .. "Summer.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rWinter |T3636846:16|t", voiceoverPath .. "Winter.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rBarrier |T253400:16|t", voiceoverPath .. "Barrier.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rDivine Hymn |T237540:16|t", voiceoverPath .. "Divine Hymn.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rGuardian Spirit |T237542:16|t", voiceoverPath .. "Guardian Spirit.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rPI |T135939:16|t", voiceoverPath .. "PI.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rPower Infusion |T135939:16|t", voiceoverPath .. "Power Infusion.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rPS |T135936:16|t", voiceoverPath .. "PS.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rPain Suppression |T135936:16|t", voiceoverPath .. "Pain Suppression.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rShroud |T635350:16|t", voiceoverPath .. "Shroud.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rTricks |T236283:16|t", voiceoverPath .. "Tricks.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rAscendence |T135791:16|t", voiceoverPath .. "Ascendence.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rHealing Tide |T538569:16|t", voiceoverPath .. "Healing Tide.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSpirit Link |T237586:16|t", voiceoverPath .. "Spirit Link.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSLT |T237586:16|t", voiceoverPath .. "SLT.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rWindrush |T538576:16|t", voiceoverPath .. "Windrush.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSS |T136210:16|t", voiceoverPath .. "SS.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSoulstone |T136210:16|t", voiceoverPath .. "Soulstone.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSummonstone |T136223:16|t", voiceoverPath .. "Summonstone.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rRallying Cry |T132351:16|t", voiceoverPath .. "Rallying Cry.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rStoneform |T136225:16|t", voiceoverPath .. "Stoneform.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rShadowmeld |T132089:16|t", voiceoverPath .. "Shadowmeld.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rWater Walking |T135863:16|t", voiceoverPath .. "Water Walking.ogg")
LSM:Register("sound", "EQOL: Trinket", voiceoverPath .. "Trinket.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rZephyr |T4630449:16|t", voiceoverPath .. "Zephyr.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rSlow Fall |T135992:16|t", voiceoverPath .. "Slow Fall.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rAura Mastery |T135872:16|t", voiceoverPath .. "Aura Mastery.ogg")
LSM:Register("sound", "EQOL: |cFF000000|rHealthstones |T538745:16|t", voiceoverPath .. "Healthstones.ogg")
LSM:Register("sound", "EQOL: Big Heal", voiceoverPath .. "Big Heal.ogg")
